services:
  - type: web
    name: kurwiel-backend
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: mysql-988fd8f-w0bise-a489.h.aivencloud.com
      - key: DB_PORT
        value: 17464
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        fromSecret: aiven_db_password
      - key: DB_NAME
        value: defaultdb
      - key: JWT_SECRET
        fromSecret: jwt_secret
      - key: FRONTEND_URL
        value: https://kurwiel.work.gd
